packages:
  - "apps/*"
  - "packages/*"
  - "packages/adapters/*"

allowBuilds:
  sharp: true # otimização de imagem do Next (binário pré-compilado)

autoInstallPeers: true
strictPeerDependencies: false
